name: Build Advanced Installer Project (.AIP)  Demo
on: [workflow_dispatch]
jobs:
  advinst-aip-build-demo:
    runs-on: windows-latest
    name: Build Aip Demo
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build AIP
        uses: caphyon/advinst-github-action@v2.0
        with:
          advinst-version: '21.9'
          advinst-license: ${{ secrets.ADVINST_LICENSE_KEY }}
          advinst-enable-automation: 'true'
          aip-path: ${{ github.workspace }}MsixTroubleshooterSetup\MsixTroubleshooterSetup.aip
          aip-build-name: DefaultBuild
          aip-package-name: MSIX Troubleshooter.msi
          aip-output-dir:  ${{ github.workspace }}\SetupPackage\MSIX Troubleshooter-SetupFiles
        
      - name: Publish setup artifact
        uses: actions/upload-artifact@v2
        with:
          name: MSIX Troubleshooter
          path: ${{ github.workspace }}\SetupPackage\MSIX Troubleshooter-SetupFiles\MSIX Troubleshooter.msi
